export const ADD_CHARACTER = "ADD_CHARACTER";
export const ADD_CHARACTERS = "ADD_CHARACTERS";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const INCREASE_CHARACTER_RANKING = "INCREASE_CHARACTER_RANKING";
export const REDUCE_CHARACTER_RANKING = "REDUCE_CHARACTER_RANKING";